# 更多细节请参考 demo: https://github.com/dongyuanxin/theme-bmw/blob/master/demo._config.yml
highlight_theme: "night eighties"

keywords: Hexo, theme-bmw

# 导航栏头部名称
nav_name: YuanXin

# 导航栏座右铭
motto: "归来仍是少年"

github: "https://github.com/dongyuanxin/"

# 站点图标和APP图标
favicon: 
  icon: /images/favicon.ico
  touch_icon: /images/touch-icon.png

# RSS文件位置
rss: 

# 自定义样式文件位置
custom_style: 

# 是否开启 分享功能: https://github.com/overtrue/share.js
social_share:
  enable: true
  sites: qzone, qq, weibo, wechat, douban, google, facebook, twitter
  disabled: 

# 页脚信息 
# start: 建站时间. 格式：YYYY-MM-DD
# more: 自定义页脚信息(支持HTML)
footer: 
  start: '2018-02-10'
  more: 

# 如何开启 评论&统计 插件：https://godbmw.com/passages/2018-11-15-theme-bmw-docs-zh/
# 请申请自己的 appid 和 appkey，并且替换下面的 appid 和 appkey
leancloud:
  appid: Hyq9wkH495DgNHWhDQCOfQSp-gzGzoHsz # 填写您的appid
  appkey: WaR7nrzhliHj9aVwdQzkdlGd # 填写您的appkey
  comment: true # 是否开启评论系统
  timer: true # 是否开启文章统计
