author: Dong Yuanxin

keywords: Hexo, theme-bmw

description: 董沅鑫的个人小站

# 导航栏头部名称
nav_name: YuanXin

# 导航栏座右铭
motto: "归来仍是少年"

github: "https://github.com/dongyuanxin/"

# 站点图标和APP图标
favicon: 
  icon: /images/favicon.ico
  touch_icon: /images/touch-icon.png

# RSS文件位置
rss: 

# 自定义样式文件位置
custom_style: 

# 更多细节请参考 demo: https://github.com/dongyuanxin/theme-bmw/blob/master/demo._config.yml
highlight_theme: "night eighties"

# 是否开启 分享功能: https://github.com/overtrue/share.js
social_share:
  enable: true
  sites: qzone, qq, weibo, wechat, douban, google, facebook, twitter
  disabled: 

# 建站时间. 格式：YYYY-MM-DD
start_time: "2018-02-10"

# 如何开启 评论&统计 插件：https://godbmw.com/passages/2018-11-15-theme-bmw-docs-zh/
# 请申请自己的 appid 和 appkey，并且替换下面的 appid 和 appkey
leancloud:
  appid: Hyq9wkH495DgNHWhDQCOfQSp-gzGzoHsz # 填写您的appid
  appkey: WaR7nrzhliHj9aVwdQzkdlGd # 填写您的appkey
  comment: true # 是否开启评论系统
  count: true # 是否开启文章统计

passwords: 
  - abc

share:
  twitter: true
  facebook: true
  weibo: true
  qq: true
  wechat: true

nav:
  -
    name: "首页"
    path: "/"
  -
    name: "归档"
    path: "/archives/"
  -
    name: "标签"
    path: "/tags/"
  -
    name: "类别"
    path: "/categories/"
  -
    name: "关于"
    path: "/about/"

footer:
  - 
    title: "博客推荐"
    children:
      - 
        name: "GodBMW"
        path: "https://godbmw.com/"
      - 
        name: "阮一峰的个人网站"
        path: "http://ruanyifeng.com/"
      -
        name: "廖雪峰的官方网站"
        path: "https://www.liaoxuefeng.com/"
  -
    title: "系列教程"
    children:
      -
        name: "webpack4系列教程"
        path: "https://godbmw.com/categories/webpack4%E7%B3%BB%E5%88%97%E6%95%99%E7%A8%8B/"
      -
        name: "设计模式手册"
        path: "https://godbmw.com/design-patterns/"
      -
        name: "Leetcode解题报告"
        path: "https://godbmw.com/leetcode/"
  -
    title: "实验室"
    children:
      -
        name: "Music API"
        path: "https://github.com/dongyuanxin/music-api-next"
      -
        name: "Webpack4 Demos"
        path: "https://github.com/dongyuanxin/webpack-demos"
      -
        name: "Theme bmw"
        path: "https://github.com/dongyuanxin/theme-bmw"
      -
        name: "金融情感分析模型"
        path: "https://github.com/dongyuanxin/news-emotion"
  -
    title: "抓到我"
    children: 
      -
        name: "掘金"
        path: "https://juejin.im/user/5b91fcf06fb9a05d3c7fd4a5"
      -
        name: "思否"
        path: "https://segmentfault.com/"
      -
        name: "简书"
        path: "https://www.jianshu.com/u/d1570f4a618a"
      -
        name: "知乎"
        path: "https://www.zhihu.com/people/godbmw/activities"
      